//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *ModelInferencePipeline) DeepCopyInto(out *ModelInferencePipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInferencePipeline.
func (in *ModelInferencePipeline) DeepCopy() *ModelInferencePipeline {
	if in == nil {
		return nil
	}
	out := new(ModelInferencePipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelInferencePipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *ModelInferencePipelineList) DeepCopyInto(out *ModelInferencePipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelInferencePipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInferencePipelineList.
func (in *ModelInferencePipelineList) DeepCopy() *ModelInferencePipelineList {
	if in == nil {
		return nil
	}
	out := new(ModelInferencePipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelInferencePipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *ModelInferencePipelineSpec) DeepCopyInto(out *ModelInferencePipelineSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInferencePipelineSpec.
func (in *ModelInferencePipelineSpec) DeepCopy() *ModelInferencePipelineSpec {
	if in == nil {
		return nil
	}
	out := new(ModelInferencePipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *ModelInferencePipelineStatus) DeepCopyInto(out *ModelInferencePipelineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInferencePipelineStatus.
func (in *ModelInferencePipelineStatus) DeepCopy() *ModelInferencePipelineStatus {
	if in == nil {
		return nil
	}
	out := new(ModelInferencePipelineStatus)
	in.DeepCopyInto(out)
	return out
}
